# aGen Color Palette
# aGen Color Palette
set -l background 1c1c1c
set -l background_alpha 42435a
set -l foreground d6dde5
set -l foreground_alpha cccccc
set -l selection 343947
set -l comment 565b74
set -l red ef1212
set -l orange 2b6ce9
set -l yellow e8b308
set -l green 9ee657
set -l purple ed2b82
set -l cyan 1db6e9
set -l pink b756f4

# Syntax Highlighting Colors
set -g fish_color_normal $foreground
set -g fish_color_command $cyan
set -g fish_color_keyword $purple
set -g fish_color_quote $green
set -g fish_color_redirection $foreground_alpha
set -g fish_color_end $cyan
set -g fish_color_error $red
set -g fish_color_param $orange
set -g fish_color_comment $comment
set -g fish_color_selection --background=$selection
set -g fish_color_search_match --background=$selection
set -g fish_color_operator $green
set -g fish_color_escape $pink
set -g fish_color_autosuggestion $comment
set -g fish_color_cancel --background=$red
set -g fish_color_search_match --background=$selection

# Completion Pager Colors
set -g fish_pager_color_progress $background --background=$green
set -g fish_pager_color_prefix $orange
set -g fish_pager_color_completion $foreground
set -g fish_pager_color_description $comment
set -g fish_pager_color_selected_background --background=$background_alpha
